name:                Script
dependencies:
- base >= 4.14 && < 5
- containers >= 0.6 && < 0.7
- tagsoup
- text
- bytestring >=0.10 && <0.12

ghc-options:
- -rtsopts=all
- -fprof-auto
- -fprof-auto-top
- -fprof-auto-calls
- -fprof-auto-exported
- -fprof-auto-calls
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -threaded 
- -Werror           # Warning as error

executables:
  script:
    main:                script.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror           # Warning as error

