name:                Script
dependencies:
- tagsoup
- base >= 4.14 && < 5
- containers >= 0.6 && < 0.7
- template-haskell >=2.18 && <3
- stm > 2.5 && < 3
- ghc-prim >= 0.6.0
- deepseq >= 1.4 && < 1.5
- fmt
- mtl >= 2.0 && < 2.3
- exceptions >= 0.10 && < 0.11
- transformers >= 0.5 && < 0.6
- transformers-base >= 0.4 && < 1
- monad-control >= 1 && < 2
- bytestring >=0.10 && <0.12
- time >=1.8 && <2
- text >=1.2 && <3
- text-show >=3.0 && <4
- extra >=1.5 && <1.8
- filepath >= 1.4.1 && < 1.5
- directory >= 1.3 && < 1.4
- optparse-applicative >= 0.17 && < 0.20
- async >= 2.2 && < 3
- attoparsec >= 0.14

ghc-options:
- -rtsopts=all
- -fprof-auto
- -fprof-auto-top
- -fprof-auto-calls
- -fprof-auto-exported
- -fprof-auto-calls
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -threaded 
- -Werror           # Warning as error

executables:
  script:
    main:                script.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror           # Warning as error

